project:
  title: kimmdy-hydrolysis
  type: website
  output-dir: docs
  render:
    - index.qmd
    - _reference
    - config.qmd
    - rates.qmd

bibliography: references.bib

website:
  page-navigation: true
  site-url: http://graeter-group.github.io/kimmdy-hydrolysis
  repo-url: https://github.com/graeter-group/kimmdy-hydrolysis
  repo-actions: [edit, issue]
  reader-mode: true
  back-to-top-navigation: true
  navbar:
    background: light
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/graeter-group/kimmdy-hydrolysis
          - text: Report a Bug
            url:  https://github.com/graeter-group/kimmdy-hydrolysis/issues/new
    left:
      - file: index.qmd
        text: Readme
      - file: _reference/index.qmd
        text: Reference
      - file: config.qmd
        text: Options
      - file: rates.qmd
        text: Rates

metadata-files:
  - _sidebar.yml

execute:
  warning: false
  echo: true
  freeze: auto

format:
  html:
    toc: true
    toc-depth: 5
    toc-expand: true
    mainfont: Roboto
    number-depth: 0
    highlight-style: arrow
    theme:
      light:
      - www/theme.scss
      dark:
      - www/theme.scss
      - www/theme-dark.scss
    code-copy: true

filters:
  - interlinks

interlinks:
  sources:
    numpy:
      url: https://numpy.org/doc/stable/
    python:
      url: https://docs.python.org/3.10/
    kimmdy:
      url: https://graeter-group.github.io/kimmdy/
      inv: objects.txt

quartodoc:
  sidebar: "_sidebar.yml"
  render_interlinks: true
  title: "References"
  style: pkgdown
  package: null
  dir: _reference
  sections:
    - title: Hydrolysis
      contents:
        - kimmdy_hydrolysis.reaction
        - kimmdy_hydrolysis.rates
        - kimmdy_hydrolysis.minisasa
        - kimmdy_hydrolysis.utils
        - kimmdy_hydrolysis.constants


